### ISSUE TITLE
Setup CI and deployment to spec.anoma.network

### ISSUE THREAD

**Issue by cwgoes** [anoma/spec#47]
For now, this should work exactly like the CI for https://docs.anoma.network - build the mdBook, and version based on the tag name, defaulting to the latest tag. I have created an [0.1.0](https://github.com/anoma/spec/releases/tag/v0.1.0) tag for the purposes of testing.

**Comment by Fraccaman** [comment]
can we close this one?

**Comment by cwgoes** [comment]
yes, thank you!
